#!/usr/bin/env node
// proto/vectors/generate.mjs — deterministic conformance-vector generator for the
// whatsacc v0 wire contracts (../pairing.md ../commands.md ../grants.md ../events.md).
//
// Fully deterministic: fixed seeds (lib.mjs), fixed timestamps, fixed nonces, and
// Ed25519 signing is itself deterministic (RFC 8032) — running this twice produces
// byte-identical JSON. Run: node proto/vectors/generate.mjs
//
// TEST KEYS ONLY — see the banner in lib.mjs.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { KEYS, SEEDS, b64u, jcs, signObject } from './lib.mjs';

const OUT = dirname(fileURLToPath(import.meta.url));

// --- Fixed constants ---------------------------------------------------------

const T0 = 1789000000; // 2026-09-10T00:26:40Z — a Thursday (matches spec examples)
const SKEW = 90; // seconds, both bounds
const MAX_CMD_WINDOW = 60; // exp - iat ceiling
const CNONCE_TTL = 30; // grant.challenge validity
const STALE_CLOCK_LIMIT = 1209600; // 2 × default grant TTL (14 days), fixed in v0
const GRANT_TTL = 604800; // 7 days

const DEVICE_ID = 'de71ce00-0000-4000-8000-000000000001';
const OTHER_DEVICE_ID = 'de71ce00-0000-4000-8000-000000000002';
const MEMBER_ID = '3e3be500-0000-4000-8000-000000000001';
const CHAT_EVENT_ID = 'c4a70000-0000-4000-8000-000000000001';
const ACCESS_POINTS = ['main', 'pedestrian']; // what this controller serves

// Deterministic 128-bit nonces: 16 bytes of a repeated byte value.
const nonce = (n) => b64u(Buffer.alloc(16, n));
const uuidN = (prefix, n) =>
  `${prefix}-0000-4000-8000-${String(n).padStart(12, '0')}`;

const utc = (y, mo, d, h, mi, s = 0) => Date.UTC(y, mo - 1, d, h, mi, s) / 1000;

// --- Helpers -----------------------------------------------------------------

/** Build a signed-vector entry: wire object + canonical bytes + signer name. */
function signedVec(signer, obj) {
  const { object, canonical } = signObject(obj, KEYS[signer]);
  return { signer, object, canonical };
}

/** Signed by `signer`, then fields mutated AFTER signing (tamper case). */
function tamperedVec(signer, obj, mutate) {
  const { object } = signObject(obj, KEYS[signer]);
  const t = { ...object };
  mutate(t);
  const { sig, ...rest } = t;
  return { signer: null, tampered_by: 'mutation after signing', object: t, canonical: jcs(rest) };
}

function unsignedVec(obj) {
  return { signer: null, unsigned: true, object: obj, canonical: jcs(obj) };
}

function writeVectors(file, doc) {
  writeFileSync(join(OUT, file), JSON.stringify(doc, null, 2) + '\n');
  console.log('wrote', file, `(${doc.vectors.length} vectors)`);
}

const HEADER = (contract) => ({
  $comment:
    'AUTOGENERATED by generate.mjs — do not edit by hand. ' +
    'TEST KEYS ONLY: all keys are public deterministic test constants; never use in production.',
  contract,
  version: 0,
  spec_constants: {
    skew_seconds: SKEW,
    max_cmd_window_seconds: MAX_CMD_WINDOW,
    cnonce_ttl_seconds: CNONCE_TTL,
    stale_clock_limit_seconds: STALE_CLOCK_LIMIT,
  },
});

// ============================================================================
// keys.json
// ============================================================================

writeFileSync(
  join(OUT, 'keys.json'),
  JSON.stringify(
    {
      $comment:
        '*** TEST KEYS ONLY — PUBLIC, DETERMINISTIC, NEVER USE IN PRODUCTION *** ' +
        'Seeds are sha256("whatsacc-test-vector:<name>"). private_seed_hex is the raw ' +
        '32-byte Ed25519 seed (RFC 8032); public_key_hex/b64u is the raw 32-byte public key.',
      keys: Object.fromEntries(
        Object.entries(KEYS).map(([name, k]) => [
          name,
          {
            private_seed_hex: SEEDS[name],
            public_key_hex: k.pubHex,
            public_key_b64u: k.pubB64u,
          },
        ])
      ),
    },
    null,
    2
  ) + '\n'
);
console.log('wrote keys.json');

// ============================================================================
// pairing.json
// ============================================================================
{
  const vectors = [];

  vectors.push({
    name: 'pair-redeem-request',
    desc: 'Valid pair.redeem request (unsigned; TLS + single-use claim token carry authenticity).',
    expect: 'accept',
    ...unsignedVec({
      v: 0,
      typ: 'pair.redeem',
      claim_token: 'dGVzdC1jbGFpbS10b2tlbi0xMjNBQkNERUZHSElKS0w',
      controller_pubkey: KEYS.controller.pubB64u,
      hw: { model: 'wacc-c1', fw: '0.1.0', ifaces: ['wifi', 'gsm'] },
    }),
  });

  vectors.push({
    name: 'pair-grant-response',
    desc: 'Valid pair.grant response (unsigned). gateway_pubkey is THE pinned key thereafter.',
    expect: 'accept',
    ...unsignedVec({
      v: 0,
      typ: 'pair.grant',
      device_id: DEVICE_ID,
      gateway_pubkey: KEYS.gateway.pubB64u,
      ws_url: 'wss://gate.example.com/api/controller/ws',
      poll_interval: 30,
    }),
  });

  const wsChallenge = {
    v: 0,
    typ: 'ws.challenge',
    cnonce: nonce(0xa1),
    iat: T0,
    exp: T0 + 30,
  };
  vectors.push({
    name: 'ws-challenge',
    desc: 'Gateway WebSocket auth challenge (unsigned).',
    expect: 'accept',
    ...unsignedVec(wsChallenge),
  });

  const wsAuthBody = {
    v: 0,
    typ: 'ws.auth',
    device_id: DEVICE_ID,
    cnonce: wsChallenge.cnonce,
    ts: T0 + 2,
  };

  vectors.push({
    name: 'ws-auth-valid',
    desc: 'Controller answers the challenge; verifies against enrolled controller key.',
    expect: 'accept',
    check: { now: T0 + 3, challenge: wsChallenge, device_id: DEVICE_ID },
    ...signedVec('controller', wsAuthBody),
  });

  vectors.push({
    name: 'ws-auth-badsig',
    desc: 'Same message signed by the wrong (attacker) key.',
    expect: 'reject',
    reason: 'badsig',
    check: { now: T0 + 3, challenge: wsChallenge, device_id: DEVICE_ID },
    ...signedVec('attacker', wsAuthBody),
  });

  vectors.push({
    name: 'ws-auth-wrong-cnonce',
    desc: 'Valid controller signature but over a cnonce the gateway never issued.',
    expect: 'reject',
    reason: 'cnonce_unknown',
    check: { now: T0 + 3, challenge: wsChallenge, device_id: DEVICE_ID },
    ...signedVec('controller', { ...wsAuthBody, cnonce: nonce(0xa2) }),
  });

  vectors.push({
    name: 'ws-auth-expired-cnonce',
    desc: 'Answer arrives after challenge.exp (30 s validity).',
    expect: 'reject',
    reason: 'cnonce_expired',
    check: { now: T0 + 40, challenge: wsChallenge, device_id: DEVICE_ID },
    ...signedVec('controller', { ...wsAuthBody, ts: T0 + 40 }),
  });

  vectors.push({
    name: 'ws-auth-stale-ts',
    desc: 'ts more than 90 s behind gateway clock.',
    expect: 'reject',
    reason: 'expired',
    check: { now: T0 + 20, challenge: wsChallenge, device_id: DEVICE_ID },
    ...signedVec('controller', { ...wsAuthBody, ts: T0 - 200 }),
  });

  writeVectors('pairing.json', { ...HEADER('pairing.md'), vectors });
}

// ============================================================================
// commands.json
// ============================================================================
{
  const vectors = [];
  let n = 0x10;
  const env = (fields) => ({
    v: 0,
    typ: 'cmd',
    device_id: DEVICE_ID,
    nonce: nonce(n++),
    iat: T0,
    exp: T0 + 30,
    ...fields,
  });
  const baseCheck = {
    now: T0 + 10,
    device_id: DEVICE_ID,
    access_points: ACCESS_POINTS,
    lockdown: false,
  };
  const cause = {
    kind: 'chat',
    channel: 'whatsapp',
    member: MEMBER_ID,
    event: CHAT_EVENT_ID,
  };

  // -- accepts, one per command ----------------------------------------------
  vectors.push({
    name: 'cmd-open-valid',
    desc: 'The canonical happy path: signed open with cause.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'main', cause })),
  });
  vectors.push({
    name: 'cmd-open-valid-no-cause',
    desc: 'cause is optional (portal/scheduled commands).',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'pedestrian' })),
  });
  vectors.push({
    name: 'cmd-hold-valid',
    desc: 'hold with optional payload.seconds.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'hold', access_point: 'main', payload: { seconds: 900 }, cause })),
  });
  vectors.push({
    name: 'cmd-close-valid',
    desc: 'close ends a hold.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'close', access_point: 'main', cause })),
  });
  vectors.push({
    name: 'cmd-lockdown-valid',
    desc: 'lockdown carries no access_point.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'lockdown' })),
  });
  vectors.push({
    name: 'cmd-ping-valid',
    desc: 'ping liveness + clock sync.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'ping' })),
  });
  vectors.push({
    name: 'cmd-config-valid',
    desc: 'config params ride in payload, covered by sig.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'config', payload: { pulse_ms: 700, hold_max: 1800, sensor_debounce_ms: 50 } })),
  });
  vectors.push({
    name: 'cmd-repair-valid',
    desc: 'repair: next gateway key in payload.next_pubkey, signed by the CURRENT pinned key.',
    expect: 'accept',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'repair', payload: { next_pubkey: KEYS.gateway_next.pubB64u } })),
  });

  // -- rejects ---------------------------------------------------------------
  vectors.push({
    name: 'cmd-badsig',
    desc: 'Envelope signed by a key that is not the pinned gateway key.',
    expect: 'reject',
    reason: 'badsig',
    check: baseCheck,
    ...signedVec('attacker', env({ cmd: 'open', access_point: 'main', cause })),
  });
  vectors.push({
    name: 'cmd-tampered',
    desc: 'Genuine gateway signature, but cmd mutated after signing (open→hold).',
    expect: 'reject',
    reason: 'badsig',
    check: baseCheck,
    ...tamperedVec('gateway', env({ cmd: 'open', access_point: 'main', cause }), (t) => {
      t.cmd = 'hold';
    }),
  });
  vectors.push({
    name: 'cmd-wrong-device',
    desc: 'device_id does not match self.',
    expect: 'reject',
    reason: 'wrong_device',
    check: baseCheck,
    ...signedVec('gateway', { ...env({ cmd: 'open', access_point: 'main' }), device_id: OTHER_DEVICE_ID }),
  });
  vectors.push({
    name: 'cmd-wrong-access-point',
    desc: 'access_point this controller does not serve.',
    expect: 'reject',
    reason: 'wrong_access_point',
    check: baseCheck,
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'vehicle' })),
  });
  vectors.push({
    name: 'cmd-expired',
    desc: 'now > exp + 90 (skew applies to BOTH bounds).',
    expect: 'reject',
    reason: 'expired',
    check: { ...baseCheck, now: T0 + 30 + SKEW + 1 },
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'main' })),
  });
  vectors.push({
    name: 'cmd-expired-boundary-accept',
    desc: 'now == exp + 90 exactly: still inside the skew window.',
    expect: 'accept',
    check: { ...baseCheck, now: T0 + 30 + SKEW },
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'main' })),
  });
  vectors.push({
    name: 'cmd-not-yet-valid',
    desc: 'now < iat - 90.',
    expect: 'reject',
    reason: 'not_yet_valid',
    check: { ...baseCheck, now: T0 - SKEW - 1 },
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'main' })),
  });
  vectors.push({
    name: 'cmd-window-too-long',
    desc: 'exp - iat > 60.',
    expect: 'reject',
    reason: 'window_too_long',
    check: baseCheck,
    ...signedVec('gateway', { ...env({ cmd: 'open', access_point: 'main' }), exp: T0 + 120 }),
  });

  // replay: same envelope delivered twice
  {
    const v = signedVec('gateway', env({ cmd: 'open', access_point: 'main', cause }));
    vectors.push({
      name: 'cmd-replay',
      desc: 'Identical envelope delivered twice; second delivery must be rejected on nonce.',
      check: baseCheck,
      steps: [
        { ...v, expect: 'accept' },
        { ...v, expect: 'reject', reason: 'replay' },
      ],
    });
  }

  // lockdown-mode matrix (commands.md rule 5)
  const lockCheck = { ...baseCheck, lockdown: true };
  vectors.push({
    name: 'cmd-lockdown-open-denied',
    desc: 'open refused during lockdown.',
    expect: 'reject',
    reason: 'lockdown',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'open', access_point: 'main', cause })),
  });
  vectors.push({
    name: 'cmd-lockdown-hold-denied',
    desc: 'hold refused during lockdown.',
    expect: 'reject',
    reason: 'lockdown',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'hold', access_point: 'main', payload: { seconds: 300 } })),
  });
  vectors.push({
    name: 'cmd-lockdown-close-denied',
    desc: 'close refused during lockdown (only lift/ping/config/repair pass).',
    expect: 'reject',
    reason: 'lockdown',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'close', access_point: 'main' })),
  });
  vectors.push({
    name: 'cmd-lockdown-lift-accepted',
    desc: 'lift is accepted during lockdown.',
    expect: 'accept',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'lift' })),
  });
  vectors.push({
    name: 'cmd-lockdown-ping-accepted',
    desc: 'ping is accepted during lockdown.',
    expect: 'accept',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'ping' })),
  });
  vectors.push({
    name: 'cmd-lockdown-repair-accepted',
    desc: 'repair is accepted during lockdown.',
    expect: 'accept',
    check: lockCheck,
    ...signedVec('gateway', env({ cmd: 'repair', payload: { next_pubkey: KEYS.gateway_next.pubB64u } })),
  });

  writeVectors('commands.json', { ...HEADER('commands.md'), vectors });
}

// ============================================================================
// grants.json
// ============================================================================
{
  const vectors = [];
  let gid = 1;
  let cn = 0x60;

  const NOW = T0 + 30800; // 2026-09-10 (Thu) 09:00:00 UTC
  const SUNDAY = utc(2026, 9, 13, 10, 0); // Sunday 10:00:00 UTC

  const grantBody = (over = {}) => ({
    v: 0,
    typ: 'grant',
    grant_id: uuidN('9aa70000', gid++),
    member: MEMBER_ID,
    app_pubkey: KEYS.app.pubB64u,
    devices: [DEVICE_ID],
    access_points: ['main', 'pedestrian'],
    windows: [{ days: 'mon-sun', from: '00:00', to: '24:00' }],
    iat: T0 - 86400,
    exp: T0 - 86400 + GRANT_TTL,
    ...over,
  });

  /**
   * Build a full transcript vector. `opts`:
   *   grantOver     — grant field overrides
   *   grantSigner   — default 'gateway'
   *   proofSigner   — default 'app'
   *   proofOver     — proof field overrides
   *   accessPoint   — requested access point (open + proof), default 'main'
   *   now           — controller clock at redemption
   *   lastSync      — last gateway clock sync
   *   lockdown
   */
  function transcriptVec(name, desc, expectation, opts = {}) {
    const now = opts.now ?? NOW;
    const ap = opts.accessPoint ?? 'main';
    const grant = signedVec(opts.grantSigner ?? 'gateway', grantBody(opts.grantOver));
    const challenge = {
      v: 0,
      typ: 'grant.challenge',
      cnonce: nonce(cn++),
      iat: now - 2,
      exp: now - 2 + CNONCE_TTL,
    };
    const proofBody = {
      v: 0,
      typ: 'grant.proof',
      grant_id: grant.object.grant_id,
      cnonce: challenge.cnonce,
      access_point: opts.proofOver?.access_point ?? ap,
      ts: now - 1,
      ...opts.proofOver,
    };
    const proof = signedVec(opts.proofSigner ?? 'app', proofBody);
    const open = unsignedVec({ v: 0, typ: 'grant.open', grant: grant.object, access_point: ap });
    return {
      name,
      desc,
      ...expectation,
      check: {
        now,
        device_id: DEVICE_ID,
        last_gateway_sync: opts.lastSync ?? now - 3600,
        lockdown: opts.lockdown ?? false,
      },
      grant,
      transcript: { open, challenge, proof },
    };
  }

  vectors.push(
    transcriptVec(
      'grant-redeem-valid',
      'Full happy-path offline redemption: fresh grant, live cnonce, app-signed proof.',
      { expect: 'accept' }
    )
  );
  vectors.push(
    transcriptVec('grant-stale-clock', 'Controller offline (no gateway clock sync) > 14 days: refuse redemption entirely.', {
      expect: 'reject',
      reason: 'stale_clock',
    }, { lastSync: NOW - STALE_CLOCK_LIMIT - 1 })
  );
  vectors.push(
    transcriptVec('grant-lockdown', 'Offline grants are refused during lockdown.', {
      expect: 'reject',
      reason: 'lockdown',
    }, { lockdown: true })
  );
  vectors.push(
    transcriptVec('grant-badsig', 'Grant signed by a key that is not the pinned gateway key.', {
      expect: 'reject',
      reason: 'badsig',
    }, { grantSigner: 'attacker' })
  );
  vectors.push(
    transcriptVec('grant-expired', 'Grant exp + 90 s is in the past.', {
      expect: 'reject',
      reason: 'expired',
    }, { grantOver: { iat: T0 - 2 * GRANT_TTL, exp: T0 - GRANT_TTL } })
  );
  vectors.push(
    transcriptVec('grant-wrong-device', 'This controller is not in grant.devices.', {
      expect: 'reject',
      reason: 'wrong_device',
    }, { grantOver: { devices: [OTHER_DEVICE_ID] } })
  );
  vectors.push(
    transcriptVec('grant-wrong-access-point', 'Requested access point is not in grant.access_points.', {
      expect: 'reject',
      reason: 'wrong_access_point',
    }, { accessPoint: 'vehicle' })
  );
  vectors.push(
    transcriptVec(
      'grant-window-denied',
      'Grant limited to mon-fri 08:00-17:00 (UTC); redemption attempted Sunday 10:00 UTC.',
      { expect: 'reject', reason: 'window' },
      {
        grantOver: { windows: [{ days: 'mon-fri', from: '08:00', to: '17:00' }] },
        now: SUNDAY,
      }
    )
  );
  vectors.push(
    transcriptVec(
      'grant-window-accepted',
      'Same mon-fri 08:00-17:00 window, redeemed Thursday 09:00 UTC: inside.',
      { expect: 'accept' },
      { grantOver: { windows: [{ days: 'mon-fri', from: '08:00', to: '17:00' }] } }
    )
  );
  vectors.push(
    transcriptVec('grant-proof-badsig', 'Proof signed by a key other than grant.app_pubkey.', {
      expect: 'reject',
      reason: 'badsig',
    }, { proofSigner: 'attacker' })
  );
  vectors.push(
    transcriptVec('grant-proof-wrong-grant', 'proof.grant_id does not match the presented grant.', {
      expect: 'reject',
      reason: 'wrong_grant',
    }, { proofOver: { grant_id: uuidN('9aa70000', 999) } })
  );
  vectors.push(
    transcriptVec('grant-cnonce-expired', 'Proof arrives after the 30 s challenge validity.', {
      expect: 'reject',
      reason: 'cnonce_expired',
    }, {
      // challenge is issued at now-2 with exp now+28; shift proof+clock past it:
      proofOver: { ts: NOW + 40 },
    })
  );
  // fix up the cnonce-expired vector: verification clock must be past challenge.exp
  vectors[vectors.length - 1].check.now = NOW + 40;
  vectors.push(
    transcriptVec('grant-proof-stale-ts', 'proof.ts more than 90 s behind the controller clock.', {
      expect: 'reject',
      reason: 'expired',
    }, { proofOver: { ts: NOW - 200 } })
  );

  // cnonce replay: identical proof presented twice against one challenge
  {
    const base = transcriptVec('grant-cnonce-replay', '', { expect: 'accept' });
    vectors.push({
      name: 'grant-cnonce-replay',
      desc: 'Same proof presented twice for one issued cnonce; second attempt rejected.',
      check: base.check,
      grant: base.grant,
      transcript: { open: base.transcript.open, challenge: base.transcript.challenge },
      steps: [
        { proof: base.transcript.proof, expect: 'accept' },
        { proof: base.transcript.proof, expect: 'reject', reason: 'cnonce_replay' },
      ],
    });
  }

  writeVectors('grants.json', { ...HEADER('grants.md'), vectors });
}

// ============================================================================
// events.json
// ============================================================================
{
  const vectors = [];
  let eid = 1;
  const evt = (kind, data, ts = T0 + 5) => ({
    v: 0,
    typ: 'event',
    event_id: uuidN('e0e70000', eid++),
    device_id: DEVICE_ID,
    kind,
    ts,
    data,
  });
  const check = { device_id: DEVICE_ID };

  const kinds = [
    ['opened', { cause: 'cmd', ref: nonce(0x10) }],
    ['closed', { cause: 'cmd', ref: nonce(0x10) }],
    ['denied', { reason: 'replay', ref: nonce(0x10) }],
    [
      'grant_redeemed',
      {
        grant_id: uuidN('9aa70000', 1),
        cnonce: nonce(0x60),
        access_point: 'main',
        proof_sig: 'see grants.json grant-redeem-valid proof.object.sig',
      },
    ],
    ['button', { button_id: 'gate-post-1' }],
    ['held_open', { seconds: 120 }],
    ['tamper', { sensor: 'enclosure' }],
    ['power', { source: 'battery', level: 87 }],
    ['net', { iface: 'gsm', rssi: -71 }],
    ['boot', { fw: '0.1.0', reason: 'watchdog' }],
  ];
  for (const [kind, data] of kinds) {
    vectors.push({
      name: `event-${kind}-valid`,
      desc: `Valid signed '${kind}' event.`,
      expect: 'accept',
      check,
      ...signedVec('controller', evt(kind, data)),
    });
  }

  vectors.push({
    name: 'event-badsig',
    desc: 'Event signed by a key that is not this device\'s enrolled controller key.',
    expect: 'reject',
    reason: 'badsig',
    check,
    ...signedVec('attacker', evt('opened', { cause: 'button', ref: 'gate-post-1' })),
  });
  vectors.push({
    name: 'event-tampered',
    desc: 'Genuine controller signature but data mutated after signing.',
    expect: 'reject',
    reason: 'badsig',
    check,
    ...tamperedVec('controller', evt('denied', { reason: 'badsig', ref: nonce(0x11) }), (t) => {
      t.data = { reason: 'badsig', ref: nonce(0x12) };
    }),
  });

  writeVectors('events.json', { ...HEADER('events.md'), vectors });
}

// ============================================================================
// acks.json
// ============================================================================
{
  const vectors = [];
  const check = { device_id: DEVICE_ID };
  const ack = (fields) => ({
    v: 0,
    typ: 'cmd.ack',
    device_id: DEVICE_ID,
    ts: T0 + 11,
    ...fields,
  });

  vectors.push({
    name: 'ack-opened',
    desc: 'Success ack for cmd-open-valid; detail omitted on success.',
    expect: 'accept',
    check,
    ...signedVec('controller', ack({ nonce: nonce(0x10), result: 'opened' })),
  });
  vectors.push({
    name: 'ack-denied-replay',
    desc: 'Denied ack with machine-readable detail.',
    expect: 'accept',
    check,
    ...signedVec('controller', ack({ nonce: nonce(0x10), result: 'denied', detail: 'replay' })),
  });
  vectors.push({
    name: 'ack-error-hw',
    desc: 'Hardware failure detail uses the hw: prefix.',
    expect: 'accept',
    check,
    ...signedVec('controller', ack({ nonce: nonce(0x12), result: 'error', detail: 'hw:relay_stuck' })),
  });
  vectors.push({
    name: 'ack-badsig',
    desc: 'Ack signed by a key that is not this device\'s enrolled controller key.',
    expect: 'reject',
    reason: 'badsig',
    check,
    ...signedVec('attacker', ack({ nonce: nonce(0x10), result: 'opened' })),
  });

  writeVectors('acks.json', { ...HEADER('commands.md#acknowledgement'), vectors });
}

console.log('done.');
